### ISSUE TITLE
vatPercentage should support decimals

### ISSUE THREAD

**Issue by JanMkl** [paytrail/api-documentation#105]
**Describe the bug**

vatPercentage is defined in the API documentation to be an integer. Snippet from the OpenAPI3 documentation:
        vatPercentage:
          type: integer
          format: int64
          example: 24
          minimum: 0
          maximum: 100
          description: Item VAT percentage

**Steps to Reproduce**

Set a float and validate against the OpenAPI definition a type error produced.

**Expected behaviour**

The type should allow floats or other type of decimal numbers.

**Actual behaviour**

.

**Screenshots**

.

**Additional context**

.

**Comment by atrotossavainen** [comment]
See #28

**Comment by atrotossavainen** [comment]
See #28

**Comment by loueranta-paytrail** [comment]
@JanMkl & @atrotossavainen: The support for decimals in VAT has now been released.

`Values between 0 and 100 are allowed with one number in decimal part.`
