### ISSUE TITLE
CIT payment requests can fail with status 400

### ISSUE THREAD

**Issue by dssjoblom** [paytrail/api-documentation#11]
We occasionally get status 400 for CIT payment requests. The error message is "Failed to create token payment". This behavior is undocumented. Why does this happen and is there something we can do to mitigate it? I can provide more information including logs upon request.

**Comment by jfrojd-paytrail** [comment]
This happens in cases where the card issuer declines the payment (no funds, expired card etc.). There is no technical way to mitigate this other than trying again later and if still fails contacting the customer to add another card.
