### ISSUE TITLE
Callback and Redirect URLs max size

### ISSUE THREAD

**Issue by gusthavosouza** [paytrail/api-documentation#17]
**Describe the bug**

When creating a payment with an URL that is too long we get an error that 
`{code=400, body={"status":"error","message":"Request payload validation failed."}`

Is there any possibility to add to the documentation the max size allowed to each field or maybe adding a better and self explanatory error message?

Thanks!

**Comment by kasperinarhi** [comment]
Hi,

It seems that compared to the old e2 interface, the new API has a lower URL max length limit. It would be helpful to have the maximum length documented as soon as possible. I do also vouch for improving the error messages of the API.

Thank you!

**Comment by jfrojd-paytrail** [comment]
That error is indeed way too generic, we will look into implementing a fix. The current limitation for the redirectUrls are 300 charactes. CallbackUrls do not have this length limitation.
