### ISSUE TITLE
Update OpenAPI specification

### ISSUE THREAD

**Issue by soskape** [paytrail/api-documentation#18]
- the endpoint '/payments/{transactionId}/token/commit' does not contain 'transactionId' path parameter definition
- the endpoint '/payments/{transactionId}/token/revert' does not contain 'transactionId' path parameter definition
- the Payment object attributes stamp and reference are in wrong order - first is 'stamp' then 'reference', but response and also the hmac calculation is calculated from the object with first 'reference' and then 'stamp'.
- the open api version is '3.0.0' instead of 3.0.0

Maybe I will find more during the implementation...

**Comment by jfrojd-paytrail** [comment]
Thank you for the notes, we'll have a look and implement necessary fixes.
