### ISSUE TITLE
Format of error response

### ISSUE THREAD

**Issue by niklaswulff** [paytrail/api-documentation#25]
What does the json schema look like when something goes wrong when creating payments?

I can't find information on how errors will be handled in the API. Say if I miscalculate the signature, or if there's data missing in the request, and lots more.

**Comment by Kepe123** [comment]
There seems to be detailed messages in the response body when ie. signature mismatches. No straight info on documentation though, but you can try it out creating different requests with postman.

**Comment by jfrojd-paytrail** [comment]
Hi @niklaswulff 

You are definitely right, this should be documented better. We will look into adding better documentation around this.
