### ISSUE TITLE
Could a success endpoint receive a "fail" status, and vice versa?

### ISSUE THREAD

**Issue by niklaswulff** [paytrail/api-documentation#27]
In the documentation for callbacks, there's a reference to the "checkout-status", which can contain any of the listed statuses

`Payment status, either ok, pending, delayed, or fail
`

If so, why do we need separate endpoints for success calls and fail calls?

```
"redirectUrls": {
    "success": "https://ecom.example.org/success",
    "cancel": "https://ecom.example.org/cancel"
  },
  "callbackUrls": {
    "success": "https://ecom.example.org/success",
    "cancel": "https://ecom.example.org/cancel"
  }
```

**Comment by jfrojd-paytrail** [comment]
Hi @niklaswulff 

A success-url cannot receive the fail status, these will always be sent to the cancel-url. Both are required so we and implementing merchants can cleanly separate the different outcomes.

**Comment by niklaswulff** [comment]
@jfrojd-paytrail So why is there a need for status properties? Wouldn't it be sufficient to use the different endpoints?
