### ISSUE TITLE
Documentation should also give examples for invalid merchant id and secret key

### ISSUE THREAD

**Issue by mikkorantalainen** [paytrail/api-documentation#38]
The URL https://docs.paytrail.com/#/?id=test-credentials list test credentials to be used for development. Currently the test credentials are as follows:

Merchant ID: 375917
Secret key: SAIPPUAKAUPPIAS

The documentation should define a way to test for invalid merchant id and/or secret key. For example, is it okay to use random data to test the API behavior if merchant id or secret key are invalid like this?

Merchant ID: 123456
Secret key: SAIPPUAKAUPPIAS
-> Invalid merchant id?

Merchant ID: 375917
Secret key: TEST
-> invalid secret?

Merchant ID: 123456
Secret key: TEST
-> invalid merchant id?

Should developers use some specific merchant id for this kind of testing to avoid spamming the Paytrail API?

**Comment by jfrojd-paytrail** [comment]
Thank you for a great suggestion @mikkorantalainen, will look into adding this to the documentation. For example 123456 and TEST are valid ways of testing this.
