### ISSUE TITLE
Documentation should explicitly say that existing E2 credentials are not okay for the current API

### ISSUE THREAD

**Issue by mikkorantalainen** [paytrail/api-documentation#39]
Software that has previously implemented the old E2 API may have existing merchant id an secret values and the documentation should explicitly say that these are not valid for the new (current) API. The new API requires acquiring new KauppiasID (sent as `checkout-account`) and Kauppiasvarmenne (used to compute `signature`) for every merchant as documented in https://support.paytrail.com/hc/fi/articles/4763684594193

**Comment by jfrojd-paytrail** [comment]
Good point, we will add this to the migration guide
