### ISSUE TITLE
Matching settlements with bank reference payments

### ISSUE THREAD

**Issue by futville** [paytrail/api-documentation#43]
In the old API, the get settlements response contains field "referenceNumber". This is the bank reference number of the bank payment from Paytrail to customer's bank account. The bank payment with this reference number comes from bank in reference payment material (saapuvat viitemaksut). Our system uses the reference number to match the bank reference payment with Paytrail settlement (+ the details/payments related to the settlement). 

In the new API there is no bank reference number in the get settlements response. Is this bank reference number included in some field of the "payment report by settlement id" response (https://docs.paytrail.com/#/?id=payment-report-request-by-settlement-id)? The documentation is not clear on the content of the fields in this response. And if it is not included, could it be added there, or how is matching between the bank payments in the saapuvat viitemaksut data and Paytrail settlements supposed to be done?

**Comment by jfrojd-paytrail** [comment]
It is currently not available in the API. We are working on adding this info to the settlement API responses and will update the documentation accordingly when this happens.
