### ISSUE TITLE
Lacking documentation regarding payment link expiration

### ISSUE THREAD

**Issue by pkoivisto** [paytrail/api-documentation#79]
I encountered a case where a transaction we had opened had expired. 
The documentation doesn't mention anything regarding expiration times for transactions, so one could be led to assume that they are open until a user has either paid or cancelled the relevant transaction. 
Is there a single standard for when transactions are to be expired, or is this perhaps something a merchant can control?
Please document the policies for expiring transactions.

Additionally, here are some improvement ideas that would suit our needs as users of the Paytrail APIs:
- allow for setting an explicit expiry time for transaction when first creating one
- Paytrail could invoke the error callback specified for the transaction when a transaction is expired

**Comment by pkoivisto** [comment]
Apparently closing a transaction will be done in about two weeks' time, according to discussion in #36. This does match our experience, but again would be good get this properly documented!

**Comment by jfrojd-paytrail** [comment]
Thanks for the feedback @pkoivisto . The expiry time is indeed two weeks. We will add this to the documentation.
